---
- block:
  - name: Updating apt repo/cache
    apt:
      update_cache: true

  - name: Upgrade all packages
    apt:
      upgrade: "full"

  - name: Installing packages
    apt:
      pkg:
        - jq
        - containerd
        - exiftool
        - git
        - openvpn
        - binwalk
        - espanso
        - fcrackzip
        - nmap
        - wireshark
        - whatweb
      state: "latest"

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

