---
- block:
  - name: Updating apt repo/cache
    apt:
      update_cache: true

  - name: Upgrade all packages
    apt:
      upgrade: "full"

  - name: Installing packages
    apt:
      pkg:
        - jq
        - containerd
        - docker.io
        - exiftool
        - git
        - openvpn
        - binwalk
        - fcrackzip
        - nmap
        - wireshark
        - whatweb
        - npm
        - p7zip
      state: "latest"
    async: true
    poll: 0

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  become: true
  become_method: sudo
