---
- name: Downloading rust install script
  get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/rustup.sh"
    ciphers: "TLSv1.2"
    mode: 0555

- name: Installing rust
  command: "/tmp/rustup.sh -y"

- name: Updating rust
  command: "{{ansible_env.HOME}}/.cargo/bin/rustup update"

- name: Info
  debug:
    msg: |
      Next step is installing the Rust tools
      However it can take a lot of time. Up to 30m is a posibility!

- name: Installing Rust tools
  command: >-
      cargo install --locked
      bat
      exa
      zoxide
      fd-find
      ripgrep
      tealdeer
      feroxbuster
