---
- block:
  - name: Cloning Git tools
    command: >-
      ruby {{ playbook_dir }}/install_git_tools.rb
      -r '{{ item.repo }}'
      -e '^{{ item.expr }}$'
      -d '{{ item.dir }}'
      -m '{{ item.mode }}'
    loop:
      - { repo: 'NationalSecurityAgency/ghidra', expr: 'ghidra_.*_PUBLIC_.*\.zip', dir: '', mode: '' }
      - { repo: 'hashcat/hashcat', expr: 'hashcat-.*.7z', dir: '', mode: '' }
      - { repo: 'diego-treitos/linux-smart-enumeration', expr: 'lse.sh', dir: '', mode: '' }
      - { repo: 'pwndbg/pwndbg', expr: 'pwndbg_.*_amd64.deb', dir: '', mode: '0755' }
      - { repo: 'carlospolop/PEASS-ng', expr: 'linpeas.sh', dir: '', mode: '' }
      - { repo: 'carlospolop/PEASS-ng', expr: 'winPEAS.bat', dir: '', mode: '' }
      - { repo: 'ffuf/ffuf', expr: 'ffuf_.*_linux_amd64.tar.gz', dir: '', mode: '' }
      - { repo: 'RickdeJager/stegseek', expr: 'stegseek_.*.deb', dir: '', mode: '0755' }
      - { repo: 'pxb1988/dex2jar', expr: 'dex-tools-v.*.zip', dir: '', mode: '' }
      - { repo: 'jpillora/chisel', expr: 'chisel_.*_linux_amd64.gz', dir: '', mode: '' }
      - { repo: 'gentilkiwi/mimikatz', expr: 'mimikatz_trunk.7z', dir: '', mode: '' }
      - { repo: 'appneta/tcpreplay', expr: 'tcpreplay-.*.tar.gz', dir: '', mode: '' }
      - { repo: 'zaproxy/zaproxy', expr: 'ZAP_WEEKLY_D-.*.zip', dir: '', mode: '' }
      - { repo: 'java-decompiler/jd-gui', expr: 'jd-gui-1.6.6.jar', dir: '', mode: '' }
      - { repo: 'ethereum/remix-desktop', expr: 'Remix-IDE-.*.AppImage', dir: '', mode: '0755' }
      - { repo: 'sonic-visualiser/sonic-visualiser', expr: 'SonicVisualiser-.*-x86_64.AppImage', dir: '', mode: '0755' }
    # Fire and forget
    async: true
    poll: 0

  - name: Cloning repositories
    git:
      repo: "https://github.com/{{ item.owner }}/{{ item.name }}"
      dest: "/opt/{{ item.name }}"
      depth: 1
      single_branch: true
    loop:
      - { owner: 'sullo', name: 'nikto' }
      - { owner: 'RsaCtfTool', name: 'RsaCtfTool' }
      - { owner: 'sqlmapproject', name: 'sqlmap' }
      - { owner: '0dayCTF', name: 'reverse-shell-generator' }
      - { owner: 'sshuttle', name: 'sshuttle' }
      - { owner: 'sherlock-project', name: 'sherlock' }
    async: true
    poll: 0

  # Radare2 is a special exception
  - name: Cloning Radare2
    git:
      repo: "https://github.com/radareorg/radare2"
      dest: "/opt/radare2"
      depth: 1
      single_branch: true

  - name: Installing Radare2
    command:
      chdir: /opt/radare2
      cmd: sys/install.sh
    ignore_errors: true
    become: false

  - name: Building RevShell Generator docker image
    command:
      chdir: /opt/reverse-shell-generator
      cmd: docker build . -t reverse_shell_generator

  - name: Installing  SSHuttle
    command:
      chdir: /opt/sshuttle
      cmd: ./setup.py install

  - name: Installing Sherlock requirements
    command:
      chdir: /opt/sherlock
      cmd: pip3 install -r requirements.txt
    ignore_errors: true
  
  become: true
  become_method: sudo
