---
- block:
    - name: Getting latest NodeJS version
      shell: curl https://nodejs.org/dist/latest-iron/ -s | grep 'node-v.*linux-x64.tar.gz' | cut -d '"' -f2
      register: node_file

    - name: Downloading latest NodeJS version
      get_url:
        url: "https://nodejs.org/dist/latest-iron/{{ node_file.stdout }}"
        dest: "/opt/{{ node_file.stdout }}"
      async: true
      poll: 0

    - name: Downloading tools
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.out_dir | default('/opt') }}/{{ item.out_file | default('') }}"
        mode: 0755
      loop:
        - { url: "https://logic2api.saleae.com/download?os=linux&arch=x64" }
        - { url: "http://www.caesum.com/handbook/Stegsolve.jar" }
        - { url: "https://portswigger.net/burp/releases/startdownload?product=community&type=Jar", out_file: "burpsuite.jar", out_dir: "/usr/share/burpsuite" }
      async: true
      poll: 0

    - name: Downloading IDA 8.4
      get_url:
        url: 'https://out7.hex-rays.com/files/idafree84_linux.run'
        dest: '/opt'
        mode: 0755

    - name: Installing IDA
      command: '/opt/idafree84_linux.run --debuglevel 3 --prefix /opt/idafree-8.4 --mode unattended'
      async: true
      poll: 0

    - name: Installing PwnTools APT dependencies
      apt:
        pkg:
          - python3
          - python3-pip
          - python3-dev
          - git
          - libssl-dev
          - libffi-dev
          - build-essential
        state: latest

    - name: Installing pip packages
      pip:
        name:
          - pip
          - pwntools
          - pwncat-cs
        state: latest
      async: true
      poll: 0

    - name: Installing WPScan
      command: gem install wpscan
      async: true
      poll: 0

  become: true
  become_method: sudo
